import Foundation

enum AppConstants {
    /// UserDefaults key mirroring the *synced* history limit for UI display.
    /// The authoritative value lives in the synced `AppSettings` record —
    /// never prune from this key alone (see ClipStore.saveAndPrune).
    static let historyLimitKey = "historyLimit"
    static let defaultHistoryLimit = 500
    static let historyLimitChoices = [100, 200, 500, 1000, 2000]

    /// UserDefaults key (macOS) for whether the capture engine is paused.
    static let capturePausedKey = "capturePaused"

    /// Maximum image payload persisted, to keep CloudKit sync snappy. Larger
    /// images are downscaled/re-encoded by the capturing platform code.
    static let maxImageByteCount = 8 * 1024 * 1024
    /// Maximum full file payload saved manually into ClipStory. Larger files
    /// should stay as external references until we add real file storage.
    static let maxManualFileByteCount = 8 * 1024 * 1024

    /// Pasteboard type markers that must never be captured: transient data
    /// and concealed content such as password-manager copies. Checked on both
    /// platforms so the lists cannot drift.
    static let excludedPasteboardTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.PasteboardConcealedType",
    ]

    /// Named pinboard colors; each platform maps these to its own Color.
    static let pinboardColorNames = [
        "magenta", "blue", "purple", "orange", "teal", "pink", "indigo", "red", "yellow", "green",
    ]

    /// SF Symbol names available as Page/Pinboard icons.
    static let pinboardIconNames = [
        "square.grid.2x2",
        "sparkles",
        "terminal",
        "curlybraces",
        "doc.text",
        "link",
        "photo",
        "folder",
        "bookmark",
        "pin",
        "star",
        "bolt",
        "hammer",
        "paintpalette",
        "briefcase",
        "person.2",
    ]
}
